DROP TABLE IF EXISTS NOTES;

CREATE TABLE NOTES (
	NOTE_ID VARCHAR(36) NOT NULL PRIMARY KEY,
	NOTE_DATE DATE NOT NULL UNIQUE,
    NOTE VARCHAR(255) NOT NULL
);

DELIMITER ;;
CREATE TRIGGER before_insert_notes
BEFORE INSERT ON NOTES
FOR EACH ROW
BEGIN
  IF new.NOTE_ID IS NULL THEN
    SET new.NOTE_ID = uuid();
  END IF;
END
;;
DELIMITER ;
